{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/edgekit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/edgekit"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit"},"metadata":{"title":"EdgeKit","roleHeading":"Framework","externalID":"EdgeKit","symbolKind":"module","modules":[{"name":"EdgeKit"}],"role":"collection"},"kind":"symbol","topicSections":[{"anchor":"Protocols","identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Anchorable","doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Construction"],"title":"Protocols","generated":true},{"identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Test"],"title":"Structures","anchor":"Structures","generated":true},{"anchor":"Type-Aliases","identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/AnchorRelation"],"generated":true,"title":"Type Aliases"},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/HorizontalEdge","doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/VerticalEdge"]},{"title":"Extended Modules","generated":true,"anchor":"Extended-Modules","identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/UIKit"]}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"Some overview"}],"type":"paragraph"}]}],"hierarchy":{"paths":[[]]},"abstract":[{"type":"text","text":"A framework which is used in UIKit for the auto layout."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit":{"url":"\/documentation\/edgekit","title":"EdgeKit","type":"topic","kind":"symbol","abstract":[{"text":"A framework which is used in UIKit for the auto layout.","type":"text"}],"identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit","role":"collection"},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/VerticalEdge":{"navigatorTitle":[{"text":"VerticalEdge","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/edgekit\/verticaledge","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VerticalEdge","kind":"identifier"}],"title":"VerticalEdge","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/VerticalEdge"},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/AnchorRelation":{"kind":"symbol","url":"\/documentation\/edgekit\/anchorrelation","title":"AnchorRelation","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnchorRelation"}],"identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/AnchorRelation","role":"symbol","type":"topic","navigatorTitle":[{"text":"AnchorRelation","kind":"identifier"}]},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/EdgeKitVersionNumber":{"url":"\/documentation\/edgekit\/edgekitversionnumber","fragments":[{"kind":"identifier","text":"EdgeKitVersionNumber"}],"type":"topic","abstract":[{"type":"text","text":"Project version number for EdgeKit."}],"kind":"symbol","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/EdgeKitVersionNumber","title":"EdgeKitVersionNumber","role":"symbol"},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/EdgeKitVersionString":{"kind":"symbol","url":"\/documentation\/edgekit\/edgekitversionstring","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/EdgeKitVersionString","abstract":[{"type":"text","text":"Project version string for EdgeKit."}],"fragments":[{"kind":"identifier","text":"EdgeKitVersionString"}],"role":"symbol","type":"topic","title":"EdgeKitVersionString"},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/HorizontalEdge":{"navigatorTitle":[{"text":"HorizontalEdge","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/HorizontalEdge","type":"topic","url":"\/documentation\/edgekit\/horizontaledge","title":"HorizontalEdge","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HorizontalEdge","kind":"identifier"}]},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/UIKit":{"url":"\/documentation\/edgekit\/uikit","kind":"symbol","role":"collection","type":"topic","abstract":[],"title":"UIKit","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/UIKit"},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/Anchorable":{"title":"Anchorable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Anchorable"}],"abstract":[],"kind":"symbol","url":"\/documentation\/edgekit\/anchorable","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Anchorable","type":"topic","role":"symbol","navigatorTitle":[{"text":"Anchorable","kind":"identifier"}]},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/Test":{"title":"Test","url":"\/documentation\/edgekit\/test","navigatorTitle":[{"kind":"identifier","text":"Test"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Test","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Test","kind":"identifier"}]},"doc://nazmiyavuz.com.EdgeKit/documentation/EdgeKit/Construction":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Construction"}],"url":"\/documentation\/edgekit\/construction","kind":"symbol","identifier":"doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/Construction","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Construction"}],"role":"symbol","title":"Construction"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Variables","identifiers":["doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/EdgeKitVersionNumber","doc:\/\/nazmiyavuz.com.EdgeKit\/documentation\/EdgeKit\/EdgeKitVersionString"],"title":"Variables","generated":true}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}